### ISSUE TITLE
Conversation.java:35-36: Add further Knowledge...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#222]
The puzzle `220-20b595ff` in [`src/main/java/com/amihaiemil/charles/github/Conversation.java`](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/github/Conversation.java) (lines 35-36) has to be resolved: "Add further Knowledge implementations, to replace the Brain class entirely."

The puzzle was created by Mihai Emil Andronache on 20-Jul-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
@0crat my skills are Java and JavaEE

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't find anything with links/link[@rel='github' and @href='opencharles/charles-rest']
	at com.zerocracy.farm.S3Farm.force(S3Farm.java:107)
	at com.zerocracy.farm.S3Farm.find(S3Farm.java:87)
	at com.zerocracy.farm.sync.SyncFarm.find(SyncFarm.java:60)
	at com.zerocracy.farm.SmartFarm.lambda$value$1(SmartFarm.java:83)
	at com.zerocracy.farm.reactive.RvFarm.find(RvFarm.java:67)
	at com.zerocracy.radars.github.GhProject.project(GhProject.java:90)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:60)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:61)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:...
```

**Comment by 0pdd** [comment]
The puzzle `220-20b595ff` has disappeared from the source code, that's why I closed this issue.
