### ISSUE TITLE
Refactor some steps

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#228]
Some steps take the JsonOBject repo as an argument in the ctor. This is not needed anymore, as perform can throw IOException if the repo cannot be read from the command right at perform time.

**Comment by amihaiemil** [comment]
@0crat hello

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalStateException: Can't find anything with links/link[@rel='github' and @href='opencharles/charles-rest']
	at com.zerocracy.farm.S3Farm.force(S3Farm.java:107)
	at com.zerocracy.farm.S3Farm.find(S3Farm.java:87)
	at com.zerocracy.farm.sync.SyncFarm.find(SyncFarm.java:60)
	at com.zerocracy.farm.SmartFarm.lambda$value$1(SmartFarm.java:83)
	at com.zerocracy.farm.reactive.RvFarm.find(RvFarm.java:67)
	at com.zerocracy.radars.github.GhProject.project(GhProject.java:90)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:60)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:61)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:...
```

**Comment by amihaiemil** [comment]
@0crat hello

**Comment by 0crat** [comment]
I'm not managing ` opencharles/charles-rest ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.

**Comment by amihaiemil** [comment]
@0crat skills

**Comment by 0crat** [comment]
I'm not managing ` opencharles/charles-rest ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.

**Comment by amihaiemil** [comment]
@SherifWaly hey Sherif, it's been a while, how are you?
Just wanted to let you know that 0crat.com (Zerocracy) will start working soon, so if you are interested in more PDD work, let me know, I can invite you. 

ZC is a service which offers automated project management, via the 0crat bot, to any client which is looking for remote devs to work in distributed style.

**Comment by SherifWaly** [comment]
@amihaiemil hey Mihai, I'm fine what about you :) ?
I'm having an internship until end of September which is fulltime and I don't have enough time for now. If work is continuing to October sure I'm interested :)

**Comment by amihaiemil** [comment]
@SherifWaly yes I'm also ok, can't complain :)
Sure, I'll keep you updated, see what happens in October

**Comment by amihaiemil** [comment]
This is done

**Comment by SherifWaly** [comment]
@amihaiemil Hi Mihai, I finished my internship now is there still more PDD work :) ?
